language: go
sudo: required
dist: trusty

go:
  - 1.7.1
  - master

before_install:
  - wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.6/rabbitmq-server_3.6.6-1_all.deb
  - sudo apt-get update
  - sudo apt-get remove rabbitmq-server
  - sudo dpkg -i rabbitmq-server_3.6.6-1_all.deb
  - sudo service rabbitmq-server start

install:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo service rabbitmq-server restart

services:
  - rabbitmq

env:
  - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/ GOMAXPROCS=2

script: make all
